# Generated by Django 2.0.2 on 2020-12-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20201125_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='singer_mobile',
            new_name='signer_mobile',
        ),
    ]
