# Generated by Django 2.0.2 on 2020-12-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20201208_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='signer_name',
            new_name='singer_name',
        ),
    ]
