# Generated by Django 2.0.2 on 2020-12-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20201208_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='singer_mobile',
            new_name='signer_mobile',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='singer_name',
            new_name='signer_name',
        ),
    ]
