# Generated by Django 2.0.2 on 2020-12-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20201208_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='signer_mobile',
            new_name='singer_mobile',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='signer_name',
            new_name='singer_name',
        ),
    ]
